<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>TRABAJO PRÁCTICO N°1</title>
  <meta name="description" content="TRABAJO PRÁCTICO N°1" />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="TRABAJO PRÁCTICO N°1" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="TRABAJO PRÁCTICO N°1" />
  
  
  

<meta name="author" content="Probabilidad y Estadística" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">


      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">TRABAJO PRÁCTICO N°1</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">TRABAJO PRÁCTICO N°1</h1>
<p class="author"><em>Probabilidad y Estadística</em></p>
</div>
<p><strong>Ejercicio 11</strong></p>
<p>Además de la resolución del ejercicio vamos a darles los comandos de R que usamos para producir los resultados. Para cargar los dados:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datos &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">84</span>, <span class="dv">85</span>, <span class="dv">87</span>, <span class="dv">72</span>, <span class="dv">88</span>, <span class="dv">87</span>, <span class="dv">86</span>, <span class="dv">88</span>, <span class="dv">80</span>, <span class="dv">82</span>, <span class="dv">88</span>, <span class="dv">76</span>, <span class="dv">75</span>, <span class="dv">85</span>, <span class="dv">81</span>, <span class="dv">93</span>, <span class="dv">84</span>, <span class="dv">80</span>,
<span class="dv">83</span>, <span class="dv">89</span>, <span class="dv">83</span>, <span class="dv">88</span>, <span class="dv">87</span>, <span class="dv">80</span>, <span class="dv">80</span>, <span class="dv">87</span>, <span class="dv">84</span>, <span class="dv">83</span>, <span class="dv">88</span>, <span class="dv">85</span>, <span class="dv">98</span>, <span class="dv">85</span>, <span class="dv">91</span>, <span class="dv">83</span>, <span class="dv">78</span>, <span class="dv">82</span>, <span class="dv">85</span>, <span class="dv">80</span>,
<span class="dv">80</span>, <span class="dv">92</span>, <span class="dv">76</span>, <span class="dv">81</span>, <span class="dv">75</span>, <span class="dv">86</span>, <span class="dv">84</span>, <span class="dv">82</span>, <span class="dv">89</span>, <span class="dv">85</span>, <span class="dv">88</span>, <span class="dv">85</span>, <span class="dv">89</span>, <span class="dv">83</span>, <span class="dv">87</span>, <span class="dv">85</span>, <span class="dv">85</span>, <span class="dv">80</span>, <span class="dv">92</span>, <span class="dv">86</span>,
<span class="dv">78</span>, <span class="dv">89</span>, <span class="dv">88</span>, <span class="dv">81</span>, <span class="dv">90</span>, <span class="dv">85</span>, <span class="dv">72</span>, <span class="dv">87</span>, <span class="dv">80</span>, <span class="dv">87</span>, <span class="dv">83</span>, <span class="dv">89</span>, <span class="dv">80</span>, <span class="dv">90</span>, <span class="dv">90</span>, <span class="dv">87</span>, <span class="dv">72</span>, <span class="dv">87</span>, <span class="dv">82</span>, <span class="dv">85</span>,
<span class="dv">78</span>, <span class="dv">80</span>, <span class="dv">90</span>, <span class="dv">77</span>, <span class="dv">84</span>, <span class="dv">84</span>, <span class="dv">89</span>, <span class="dv">79</span>, <span class="dv">81</span>, <span class="dv">85</span>)</code></pre></div>
<p><strong>a) Distribución de frecuencias con intervalos de amplitud 5.</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">intervalos &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">70</span>,<span class="dv">100</span>,<span class="dv">5</span>)
tabla &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">table</span>(<span class="kw">cut</span>(datos,intervalos)))
tabla</code></pre></div>
<pre><code>##       Var1 Freq
## 1  (70,75]    5
## 2  (75,80]   17
## 3  (80,85]   32
## 4  (85,90]   29
## 5  (90,95]    4
## 6 (95,100]    1</code></pre>
<p><strong>b) Trazar el histograma y el polígono.</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">histograma &lt;-<span class="st"> </span><span class="kw">hist</span>(datos, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">65</span>,<span class="dv">105</span>), <span class="dt">xlab =</span> <span class="st">&quot;Puntajes&quot;</span>, <span class="dt">ylab =</span>
<span class="st">&quot;Frecuencia&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Histograma de puntajes&quot;</span>)
<span class="kw">lines</span>(<span class="kw">c</span>(<span class="fl">67.5</span>,histograma<span class="op">$</span>mids,<span class="fl">102.5</span>), <span class="kw">c</span>(<span class="dv">0</span>,histograma<span class="op">$</span>counts,<span class="dv">0</span>))</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p><strong>c) Formar la distribución de porcentajes acumulados.</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tabla<span class="op">$</span>FrecRel &lt;-<span class="st"> </span>tabla<span class="op">$</span>Freq<span class="op">/</span><span class="kw">sum</span>(tabla<span class="op">$</span>Freq)
tabla<span class="op">$</span>RelPor &lt;-<span class="st"> </span>tabla<span class="op">$</span>FrecRel<span class="op">*</span><span class="dv">100</span>
tabla<span class="op">$</span>PorAcu &lt;-<span class="st"> </span><span class="kw">cumsum</span>(tabla<span class="op">$</span>RelPor)
tabla</code></pre></div>
<pre><code>##       Var1 Freq    FrecRel    RelPor     PorAcu
## 1  (70,75]    5 0.05681818  5.681818   5.681818
## 2  (75,80]   17 0.19318182 19.318182  25.000000
## 3  (80,85]   32 0.36363636 36.363636  61.363636
## 4  (85,90]   29 0.32954545 32.954545  94.318182
## 5  (90,95]    4 0.04545455  4.545455  98.863636
## 6 (95,100]    1 0.01136364  1.136364 100.000000</code></pre>
<p><strong>d) ¿Cuál es el puntaje más típico?</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(datos)</code></pre></div>
<pre><code>## datos
## 72 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 98 
##  3  2  2  1  3  1 10  4  4  6  6 12  3  9  7  6  4  1  2  1  1</code></pre>
<p>El puntaje más típico es 85. Este puntaje se repite 12 veces. Es la moda de la muestra. Si no contáramos con los datos originales sino con la tabla de frecuencia por intervalos, diríamos que el valor más típico está en el intervalo (80,85] que es la marca de clase del intervalo con mayor frecuencia.</p>
<p><strong>e) ¿Cuál es el recorrido de los puntajes?</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">max</span>(datos) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(datos)</code></pre></div>
<pre><code>## [1] 26</code></pre>
<p>El puntaje máximo es 98 y el puntaje mínimo es 72, por lo tanto el recorrido es 22 (98-76 = 22).</p>
<p><strong>f) ¿Qué porcentaje de estudiantes tuvo un puntaje de menos de 80?</strong></p>
<p>Observando en la tabla las frecuencias porcentuales acumuladas, podemos decir que el 25% tuvo un puntaje menor o igual a 80. Si no contáramos con los datos, esta debería ser nuestra respuesta definitiva ya que no podemos saber exactamente cuántos datos alcanzaron 80. De hecho al utilizar intervalos estamos trabajando la variable como continua y suponiendo que dentro del intervalo hay una distribución uniforme de los datos con lo cual sería correcto asumir que el 25% tuvo un puntaje menor a 80. Al contar con los datos, podríamos construir los intervalos de manera que se incluya en el extremo izquierdo en vez del derecho, entonces la tabla nos queda:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tabla2 &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">table</span>(<span class="kw">cut</span>(datos,intervalos, <span class="dt">right =</span> <span class="ot">FALSE</span>)))
tabla2<span class="op">$</span>FrecRel &lt;-<span class="st"> </span>tabla2<span class="op">$</span>Freq<span class="op">/</span><span class="kw">sum</span>(tabla2<span class="op">$</span>Freq)
tabla2<span class="op">$</span>RelPor &lt;-<span class="st"> </span>tabla2<span class="op">$</span>FrecRel<span class="op">*</span><span class="dv">100</span>
tabla2<span class="op">$</span>PorAcu &lt;-<span class="st"> </span><span class="kw">cumsum</span>(tabla2<span class="op">$</span>RelPor)
tabla2</code></pre></div>
<pre><code>##       Var1 Freq    FrecRel    RelPor     PorAcu
## 1  [70,75)    3 0.03409091  3.409091   3.409091
## 2  [75,80)    9 0.10227273 10.227273  13.636364
## 3  [80,85)   30 0.34090909 34.090909  47.727273
## 4  [85,90)   37 0.42045455 42.045455  89.772727
## 5  [90,95)    8 0.09090909  9.090909  98.863636
## 6 [95,100)    1 0.01136364  1.136364 100.000000</code></pre>
<p>Ahora podemos decir que aproximadamente el 13.64% de los estudiantes tuvo un puntaje menor a 80.</p>
<p><strong>g) El 85% de los estudiantes tuvo puntajes menores ¿a qué valor?</strong></p>
<p>Lo que nos esta pidiendo el problema es que calculemos el percentil 85. Al observar las frecuencias porcentuales acumuladas vemos que el dato que llegaría al 85% se encuentra en el intervalo [85, 90). El total de datos que tenemos es de 88, con lo cual aplicando la fórmula P85=Linf+c((95N/100)-Fi-1)/fi tenemos P85=85+5(95*88/100)-47.73)/42.05 y nos da como resultado 89,27. Es decir que el 85% tuvo un puntaje menor a 89.27.</p>
<p><strong>h)¿Qué forma tiene la distribución de los datos? Realizar un box plot.</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(datos, <span class="dt">horizontal =</span> <span class="ot">TRUE</span>)
<span class="kw">text</span>(<span class="dt">x =</span> <span class="kw">boxplot.stats</span>(datos)<span class="op">$</span>stats, <span class="dt">labels =</span> <span class="kw">boxplot.stats</span>(datos)<span class="op">$</span>stats, <span class="dt">y =</span><span class="fl">1.25</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p><strong>i) Calcular las medidas de dispersión que considere apropiadas.</strong></p>
<p>El rango es 26 (98-72=26). El recorrido intercuartilico es 7 (87.5-80.5 = 7). La gran diferencia entre el rango y el recorrido intercuartílico nos indica que hay una concentración importante del 50% centrales de los datos y una mayor dispersión del resto.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(datos)</code></pre></div>
<pre><code>## [1] 23.98211</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(datos)</code></pre></div>
<pre><code>## [1] 4.897153</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(datos)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   72.00   80.75   85.00   84.08   87.25   98.00</code></pre>
<p>La varianza es de 23.98211 y el desvío estándar de 4.897153. Para analizar estos estadísticos es necesario conocer la media, cuyo valor es 84.08. A partir de este valor y de la desviación estándar podemos concluir, apoyados incluso por el histograma, que hay una concentración de los datos alrededor de la media. Además no se observar un sesgo importante ni a derecha ni a izquierda.</p>
<!-- If you need PDF output, uncomment bookdown::pdf_book above in YAML. You will need a LaTeX installation, e.g., https://yihui.name/tinytex/ -->

            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
